Feature/movie searcher
Veron116/movie-searcher pull request #1
Opened 2020-01-26 08:57 UTC by Veron116

2020-01-26 17:25 UTC, Geschoss requested changes

2020-01-26 17:25 UTC, Geschoss commented on src/movies/IMovie.tsx
> +export interface IMovie {
Отлично что вынесла в отдельный файл.
Можно даже создать папку `typings`  будет еще круче

2020-01-26 17:25 UTC, Geschoss commented on src/movies/List.tsx
> +    const [activeCardId, setActiveCardId] = useState<number>();
Очень круто что ты сделала эту логику=)
Давай теперь попробуем  сделать что бы на клавиши вправо/влево все это работало, будет вообще огонь=)
Еще лучше указывать начальное значени `const [activeCardId, setActiveCardId] = useState<number>(0);`

2020-01-26 17:25 UTC, Geschoss commented on src/movies/List.tsx
> +    function getMovieIndex(id: number) {
Давай сделаем отдельный файл `utils.ts` и туда будем скидывать вот такие функции.
А что бы сделать ее еще лучше и ближе к чистым функциям давай сделам что бы она принимала массив фильмов и id и возвращала индекс. Типа 
`getMovieIndex(id: number, movies: IMovie[])`

2020-01-26 17:25 UTC, Geschoss commented on src/movies/List.tsx
> +        fetch('https://devlab.website/v1/movies')
Давай вынесем эту url в переменную
const MOVIES_URL = 'https://devlab.website/v1/movies'
Старайся подобные вещи сразу выносить в константы.
Создай файл constants.ts и пусть там хранятся все константы.

2020-01-26 17:25 UTC, Geschoss commented on src/movies/List.tsx
> +    }, [activeCardId]);
А зачем нам тут `activeCardId`?
Открой нетворки в браузере и посмотри каждый раз там дергается запрос, мне кажется это излишним

2020-01-26 17:25 UTC, Geschoss commented on src/movies/List.tsx
> +            if (index !== undefined && index >= 1) {
Давай попробуем зациклить эту штуку, то есть переходить к первому если мы на послденем и наоборот=)

2020-01-26 17:25 UTC, Geschoss commented on src/movies/List.tsx
> +        if (activeCardId !== undefined) {
Давай все же попробуем сделать дефолтное значение и избавиться от `undefined`

2020-01-26 17:25 UTC, Geschoss commented on src/movies/List.tsx
> +                {movies.map((item: any) => {
`any` не наш вариант=)
Мне кажется тут ts даже сам может определить тип

2020-01-26 17:25 UTC, Geschoss commented on src/movies/Movie.tsx
> +export const MovieRenderFunc = (props: any) => {
хм странное название, давай придумаем что то простое. Это же просто карточка фильма=)

2020-01-26 17:25 UTC, Geschoss commented on src/App.tsx
> +    return (
Отлично, мне понравилось.
Давай еще добавим эедер для карасоты

2020-01-27 13:39 UTC, Veron116 commented on src/movies/IMovie.tsx
> +export interface IMovie {
done

2020-01-27 13:39 UTC, Veron116 commented on src/movies/List.tsx
> +        fetch('https://devlab.website/v1/movies')
done

2020-01-27 13:39 UTC, Veron116 commented on src/movies/List.tsx
> +            if (index !== undefined && index >= 1) {
done

2020-01-27 13:39 UTC, Veron116 commented on src/movies/Movie.tsx
> +export const MovieRenderFunc = (props: any) => {
done

2020-01-27 13:42 UTC, Veron116 commented on src/movies/List.tsx
> +                {movies.map((item: any) => {
done

2020-01-27 13:54 UTC, Veron116 commented on src/movies/List.tsx
> +    const [activeCardId, setActiveCardId] = useState<number>();
> Давай теперь попробуем сделать что бы на клавиши вправо/влево все это работало, будет вообще огонь=)
так все работало жеж О_о

если задать начальное значение = 0, то id активного элемента вместо того чтобы передать в качестве параметра в карточку movies[activeCardId].id передается просто 0. Поэтому я в fetch начальное значение задаю вот так
`if (activeCardId === undefined) {
     setActiveCardId(json[0].id);
 }`

2020-01-27 14:12 UTC, Veron116 commented on src/movies/List.tsx
> +    function getMovieIndex(id: number) {
done

2020-01-27 14:17 UTC, Veron116 commented on src/movies/List.tsx
> +    }, [activeCardId]);
Да, я знаю. И надеялась что после ревью ситуация прояснится, но она магическим образом после всех метаморфоз самоизлечилась. Магия...

2020-01-27 14:20 UTC, Veron116 commented on src/movies/List.tsx
> +        if (activeCardId !== undefined) {
Это был "костыль" потому что иначе не работало)) Получалось так что, на момент когда был нужен нулевой элемент массива в fetch он возвращал undefined и в консоли падала ошибка. Поэтому я вот так криво хакнула систему. Сейчас порефакторила по твоим комментам и этот костыль тоже самоизлечился.

2020-01-27 15:05 UTC, Veron116 commented on src/App.tsx
> +    return (
Готовченко!

2020-01-31 03:53 UTC, Geschoss approved these changes

2020-01-31 16:49 UTC, kirzharov commented
Можно смержить 👍

2020-02-03 12:50 UTC, kirzharov commented
@Veron116, нужно вынести коммиты для нового задания, смежить данный пулл-реквест в мастер и продолжить работу в новой ветке.

2020-02-03 15:14 UTC, merged